version: '3.8'

services:
  ceramic-one:
    image: public.ecr.aws/r5b3e0r5/3box/ceramic-one:latest
    network_mode: "host"
    command: "--network dev-unstable"
    volumes:
      - ceramic-one-data:/home/daniel/.ceramic
volumes:
  ceramic-one-data:
    driver: local
